name: Keep Alive Ping

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Server Root Endpoint
        run: curl -I https://threads-ai-bot.onrender.com  # 실제 Render URL로 변경하세요.
