name: Trigger /runbot Endpoint Every 30m

on:
  schedule:
    - cron: "*/30 * * * *"  # 매 30분마다 실행
  workflow_dispatch:      # 수동 실행도 가능

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Call /runbot endpoint
        run: curl -X GET https://threads-ai-bot.onrender.com/runbot
